### ISSUE TITLE
Many navigations can happen in a second with power users

### ISSUE THREAD

**Issue by dieulot** [yoavweiss/soft-navigations#1]
> Finally, we should consider limiting the amount of soft navigation detected in a certain timeframe (**e.g. 1 per X seconds**).

I used to run a third-party web app for very active forums where pages displayed instantly and the whole design was tuned for efficiency. Because you don’t know if a thread you clicked on would be interesting content or short-form garbage it wasn’t unconceivable to 1. click on a forum, 2. click on a thread, 3. go back with your mouse’s back button, 4. move your mouse just a tiny bit and click on another thread; in the span of one second.

Other tools that aren’t dynamic but need multiple clicks/taps to access a regularly-needed feature could have a similar number of navigations. I once saw a ~30 years old handyman do so (3 or 4 navigations in 1 or 1.5 seconds) with a specialized app on a tablet.

A maximum of 5 navigations per second would probably be enough for every use case, though I’m not sure. 10 would be.

More granularly, more than 1 navigation per 100 ms might happen with an interface where you know you have to click at the same place on two different pages, so one learns to just effectively double click. That’s a very extreme case though, but it might be easier for web developers not to have to deal with it.

**Comment by yoavweiss** [comment]
Thanks for the feedback. I'll modify it to say "X per Y seconds".
