### ISSUE TITLE
Is fairer RUM-representation a usecase?

### ISSUE THREAD

**Issue by Suven** [yoavweiss/soft-navigations#6]
Hey (:

First of all, thanks for your repo/and team efforts. I just learned about this today on perfnow.nl and am really looking forward to testing this on our platforms in the next few days!

I'm unsure whether or not my feedback is misplaced since this doc is more targeted at the API and not its impacts on the ecosystem. OR it maybe is just too obvious? However, my motivation/anticipation comes from this:

- We ship an SPA for better UX (our users will open multiple pages of the same type where just a few data sets are swapped)
- CWV are picked for UX-consideration
- Having only the first (by nature slowest [especially with stuff like consent-handling]) page represented in RUM/CrUX does not 'fairly' represent the performance an SPA-user experiences through his session
- From my understanding, this means that shipping an SPA is ultimately penalized or at least not represented fairly in the field data that is used by Google as a ranking factor

**Comment by yoavweiss** [comment]
I don't think it's a direct use-case of the API discussed here, but at the same time, from my personal perspective, this effort definitely falls into the scope discussed in https://web.dev/vitals-spa-faq. Hope that helps! :)
